swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Owner
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /owner:
    get:
      operationId: owner.read_all
      tags:
        - owner
      summary: Read the entire list of numbers
      description: Read the list of numbers
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of numbers to get from numbers
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering numbers
          required: false
      responses:
        200:
          description: Successfully read numbers list operation
          schema:
            type: array
            items:
              properties:
                result:
                  type: integer
                timestamp:
                  type: string

    post:
      operationId: owner.store
      tags:
        - owner
      summary: The owner data structure supported by the server application
      description: Result
      parameters:
        - name: number
          in: body
          description: Number to store
          required: True
          schema:
            type: object
            properties:
              result:
                type: integer
                description: Number to store
      responses:
        201:
          description: Successfully store number
